name: casa
favicon: null
layout_spectrum: 0.6504091676324606
typography_spectrum: 0.0018973243422806263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.755512488540262
  lightness: 0.40593789145350456
  saturation: 0.761603454593569
  rhythmicContrast: 0.7693108036182821
purpose: []
