name: casa
favicon: null
layout_spectrum: 0.6504091676324606
typography_spectrum: 0.0018973243422806263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d282e'
    - '#2a3b43'
    - '#394d58'
    - '#4c6876'
    - '#5c7d8e'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
